environment:
    matrix:
      - TARGET: x86_64-pc-windows-msvc
        BITS: 64
        MSYS2: 1
        SODIUM_BUILD_STATIC: yes
      - TARGET: i686-pc-windows-gnu
        BITS: 32
        MSYS2: 1
        SODIUM_BUILD_STATIC: yes

install:
    - git submodule update --init --recursive
    # Install Rust
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%

    # Run tests
    - rustc -V
    - cargo -V

build: false

test_script:
    - cargo test -v --no-fail-fast

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
